[package]
name = "kcapi-sys"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
bindgen = "0.53"
autotools = "0.2"

[dependencies]