on:
  - push
  - pull_request

name: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: install autotools
        run: |
          sudo apt-get install -y autotools

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings